services:
    surrealdb:
        image: surrealdb/surrealdb:v2
        command: ['start', '--user', 'symfony', '--pass', 'symfony']
        environment:
            SURREAL_HTTP_MAX_KEY_BODY_SIZE: 49152
        ports:
            - '8000:8000'
