<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Config\Definition\Configurator;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;

return (new ArrayNodeDefinition('workflow'))
    ->useAttributeAsKey('name')
    ->arrayPrototype()
        ->children()
            ->scalarNode('workflow')
                ->isRequired()
                ->cannotBeEmpty()
                ->info('Name of an existing Symfony Workflow (registered as "workflow.<name>" service)')
            ->end()
            ->arrayNode('executors')
                ->isRequired()
                ->requiresAtLeastOneElement()
                ->useAttributeAsKey('place')
                ->arrayPrototype()
                    ->children()
                        ->enumNode('type')
                            ->values(['agent', 'service'])
                            ->isRequired()
                        ->end()
                        ->scalarNode('agent')
                            ->info('Agent name (references ai.agent.<name>) — required for type: agent')
                            ->cannotBeEmpty()
                        ->end()
                        ->scalarNode('input_key')
                            ->defaultValue('input')
                        ->end()
                        ->scalarNode('output_key')
                            ->defaultValue('output')
                        ->end()
                        ->scalarNode('service')
                            ->info('Service ID implementing ExecutorInterface — required for type: service')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                    ->validate()
                        ->ifTrue(static fn (array $v): bool => 'agent' === $v['type'] && !isset($v['agent']))
                        ->thenInvalid('Executor type "agent" requires the "agent" option.')
                    ->end()
                    ->validate()
                        ->ifTrue(static fn (array $v): bool => 'service' === $v['type'] && !isset($v['service']))
                        ->thenInvalid('Executor type "service" requires the "service" option.')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('store')
                ->addDefaultsIfNotSet()
                ->children()
                    ->enumNode('type')
                        ->values(['memory', 'cache', 'filesystem', 'redis', 'service'])
                        ->defaultValue('memory')
                    ->end()
                    ->scalarNode('cache_service')
                        ->info('PSR-6 cache pool service ID (for type: cache)')
                        ->defaultValue('cache.app')
                    ->end()
                    ->scalarNode('prefix')
                        ->info('Key prefix for cache/redis stores')
                        ->defaultValue('_workflow_state_')
                    ->end()
                    ->integerNode('ttl')
                        ->info('TTL in seconds (for type: cache)')
                        ->defaultValue(86400)
                    ->end()
                    ->scalarNode('directory')
                        ->info('Directory path (for type: filesystem)')
                    ->end()
                    ->scalarNode('redis_client')
                        ->info('Redis client service ID (for type: redis)')
                    ->end()
                    ->scalarNode('service')
                        ->info('Custom service ID implementing WorkflowStateStoreInterface (for type: service)')
                    ->end()
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $v): bool => 'filesystem' === $v['type'] && !isset($v['directory']))
                    ->thenInvalid('Store type "filesystem" requires the "directory" option.')
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $v): bool => 'redis' === $v['type'] && !isset($v['redis_client']))
                    ->thenInvalid('Store type "redis" requires the "redis_client" option.')
                ->end()
                ->validate()
                    ->ifTrue(static fn (array $v): bool => 'service' === $v['type'] && !isset($v['service']))
                    ->thenInvalid('Store type "service" requires the "service" option.')
                ->end()
            ->end()
            ->arrayNode('guards')
                ->useAttributeAsKey('place')
                ->arrayPrototype()
                    ->scalarPrototype()->cannotBeEmpty()->end()
                ->end()
            ->end()
            ->scalarNode('transition_resolver')
                ->defaultNull()
                ->info('Service ID of a custom TransitionResolverInterface, or null for default')
            ->end()
        ->end()
    ->end();
