<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\AI\Platform\Contract\JsonSchema;

use Symfony\Component\Serializer\NameConverter\NameConverterInterface;

/**
 * Maps PHP property names to the JSON keys generated by the JSON schema factory.
 *
 * It is limited to `#[Schema(name: '...')]` and ignores every other naming metadata, notably
 * `#[SerializedName]`, because the schema ignores those too and both sides have to agree.
 *
 * @author Johannes Wachter <johannes@sulu.io>
 */
final class SchemaNameConverter implements NameConverterInterface
{
    public function normalize(string $propertyName, ?string $class = null, ?string $format = null, array $context = []): string
    {
        if (null === $class) {
            return $propertyName;
        }

        return SchemaNameResolver::forClass($class)[$propertyName] ?? $propertyName;
    }

    public function denormalize(string $propertyName, ?string $class = null, ?string $format = null, array $context = []): string
    {
        if (null === $class) {
            return $propertyName;
        }

        $propertyNames = array_flip(SchemaNameResolver::forClass($class));

        return $propertyNames[$propertyName] ?? $propertyName;
    }
}
