name: Monorepo Split (Symfony AI)

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  workflow_dispatch:

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (Go, libgit2 etc)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config libgit2-dev
          # install Go (if not already)
          sudo apt-get install -y golang-go

      - name: Fetch splitsh lite v2.0.0 source
        run: |
          curl -L https://github.com/splitsh/lite/archive/refs/tags/v2.0.0.tar.gz -o splitsh-lite.tar.gz
          tar xf splitsh-lite.tar.gz
          cd lite-2.0.0
          # Build (per README instructions)
          go build -o ../splitsh-lite .

      - name: Install splitsh-lite binary
        run: |
          chmod +x splitsh-lite
          mv splitsh-lite /usr/local/bin/splitsh-lite
          splitsh-lite --version || true

      - name: Set up SSH for pushing
        env:
          SSH_KEY: ${{ secrets.SPLIT_PUSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Define packages & split & push
        run: |
          cat > packages.json <<'JSON'
          [
            { "prefix": "src/platform",   "repo": "git@github.com:YOUR_ORG/ai-platform.git",  "branch": "main" },
            { "prefix": "src/agent",      "repo": "git@github.com:YOUR_ORG/ai-agent.git",     "branch": "main" },
            { "prefix": "src/store",      "repo": "git@github.com:YOUR_ORG/ai-store.git",     "branch": "main" },
            { "prefix": "src/mcp-sdk",    "repo": "git@github.com:YOUR_ORG/mcp-sdk.git",      "branch": "main" },
            { "prefix": "src/ai-bundle",  "repo": "git@github.com:YOUR_ORG/ai-bundle.git",    "branch": "main" },
            { "prefix": "src/mcp-bundle", "repo": "git@github.com:YOUR_ORG/mcp-bundle.git",   "branch": "main" }
          ]
          JSON

          git fetch --all --tags
          jq -c '.[]' packages.json | while read -r row; do
            prefix=$(echo "$row" | jq -r '.prefix')
            repo=$(echo "$row"   | jq -r '.repo')
            branch=$(echo "$row" | jq -r '.branch')
            echo "::group::Splitting $prefix -> $repo ($branch)"
            commit=$(splitsh-lite --prefix="$prefix")
            if [ -z "$commit" ]; then
              echo "No commit produced for $prefix; skipping."
              echo "::endgroup::"
              continue
            fi
            split_branch="${prefix//\//-}-split"
            git update-ref "refs/heads/$split_branch" "$commit"
            git push "$repo" "refs/heads/$split_branch:$branch" --force
            echo "::endgroup::"
          done

  split-tags:
    name: Split on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies (Go, libgit2)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config libgit2-dev golang-go

      - name: Fetch & build splitsh-lite
        run: |
          curl -L https://github.com/splitsh/lite/archive/refs/tags/v2.0.0.tar.gz -o splitsh-lite.tar.gz
          tar xf splitsh-lite.tar.gz
          cd lite-2.0.0
          go build -o ../splitsh-lite .
          chmod +x splitsh-lite
          mv splitsh-lite /usr/local/bin/splitsh-lite
          splitsh-lite --version || true

      - name: Set up SSH for pushing
        env:
          SSH_KEY: ${{ secrets.SPLIT_PUSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Define packages & split tags
        env:
          TAG: ${{ github.ref_name }}
        run: |
          cat > packages.json <<'JSON'
          [
            { "prefix": "src/platform",   "repo": "git@github.com:YOUR_ORG/ai-platform.git"  },
            { "prefix": "src/agent",      "repo": "git@github.com:YOUR_ORG/ai-agent.git"     },
            { "prefix": "src/store",      "repo": "git@github.com:YOUR_ORG/ai-store.git"     },
            { "prefix": "src/mcp-sdk",    "repo": "git@github.com:YOUR_ORG/mcp-sdk.git"      },
            { "prefix": "src/ai-bundle",  "repo": "git@github.com:YOUR_ORG/ai-bundle.git"    },
            { "prefix": "src/mcp-bundle", "repo": "git@github.com:YOUR_ORG/mcp-bundle.git"   }
          ]
          JSON

          git fetch --all --tags
          jq -c '.[]' packages.json | while read -r row; do
            prefix=$(echo "$row" | jq -r '.prefix')
            repo=$(echo "$row"   | jq -r '.repo')
            echo "::group::Splitting tag $TAG for $prefix -> $repo"
            commit=$(splitsh-lite --prefix="$prefix" --origin="refs/tags/$TAG" || true)
            if [ -z "$commit" ]; then
              echo "No split commit for $prefix at tag $TAG; skipping."
              echo "::endgroup::"
              continue
            fi
            git tag -f "$TAG" "$commit"
            git push "$repo" "refs/tags/$TAG" --force
            echo "::endgroup::"
          done
