name: Monorepo Split (Symfony AI)

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  workflow_dispatch:

jobs:
  split-branches:
    name: Split on branch pushes
    if: ${{ github.event_name != 'push' || startsWith(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install splitsh-lite
        run: |
          curl -L https://github.com/splitsh/lite/releases/download/v1.0.1/splitsh-lite_linux_amd64 \
            -o /usr/local/bin/splitsh-lite
          chmod +x /usr/local/bin/splitsh-lite

      - name: Set up SSH for pushing
        env:
          SSH_KEY: ${{ secrets.SPLIT_PUSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Define packages
        id: pkgs
        run: |
          cat > packages.json <<'JSON'
          [
            { "prefix": "src/platform",   "repo": "git@github.com:YOUR_ORG/ai-platform.git",  "branch": "main" },
            { "prefix": "src/agent",      "repo": "git@github.com:YOUR_ORG/ai-agent.git",     "branch": "main" },
            { "prefix": "src/store",      "repo": "git@github.com:YOUR_ORG/ai-store.git",     "branch": "main" },
            { "prefix": "src/mcp-sdk",    "repo": "git@github.com:YOUR_ORG/mcp-sdk.git",      "branch": "main" },
            { "prefix": "src/ai-bundle",  "repo": "git@github.com:YOUR_ORG/ai-bundle.git",    "branch": "main" },
            { "prefix": "src/mcp-bundle", "repo": "git@github.com:YOUR_ORG/mcp-bundle.git",   "branch": "main" }
          ]
          JSON

      - name: Split & push each package
        run: |
          set -euo pipefail
          git fetch --all --tags
          jq -c '.[]' packages.json | while read -r row; do
            prefix=$(echo "$row" | jq -r '.prefix')
            repo=$(echo "$row"   | jq -r '.repo')
            branch=$(echo "$row" | jq -r '.branch')

            echo "::group::Splitting $prefix -> $repo ($branch)"
            commit=$(splitsh-lite --prefix="$prefix")
            if [ -z "$commit" ]; then
              echo "No commit produced for $prefix; skipping."
              echo "::endgroup::"
              continue
            fi
            split_branch="${prefix//\//-}-split"
            git update-ref "refs/heads/$split_branch" "$commit"
            git push "$repo" "refs/heads/$split_branch:$branch" --force
            echo "::endgroup::"
          done

  split-tags:
    name: Split on tag pushes
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install splitsh-lite
        run: |
          curl -L https://github.com/splitsh/lite/releases/download/v1.0.1/splitsh-lite_linux_amd64 \
            -o /usr/local/bin/splitsh-lite
          chmod +x /usr/local/bin/splitsh-lite

      - name: Set up SSH for pushing
        env:
          SSH_KEY: ${{ secrets.SPLIT_PUSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Define packages
        run: |
          cat > packages.json <<'JSON'
          [
            { "prefix": "src/platform",   "repo": "git@github.com:YOUR_ORG/ai-platform.git"  },
            { "prefix": "src/agent",      "repo": "git@github.com:YOUR_ORG/ai-agent.git"     },
            { "prefix": "src/store",      "repo": "git@github.com:YOUR_ORG/ai-store.git"     },
            { "prefix": "src/mcp-sdk",    "repo": "git@github.com:YOUR_ORG/mcp-sdk.git"      },
            { "prefix": "src/ai-bundle",  "repo": "git@github.com:YOUR_ORG/ai-bundle.git"    },
            { "prefix": "src/mcp-bundle", "repo": "git@github.com:YOUR_ORG/mcp-bundle.git"   }
          ]
          JSON

      - name: Split & push tag to each package repo
        env:
          TAG: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git fetch --all --tags
          jq -c '.[]' packages.json | while read -r row; do
            prefix=$(echo "$row" | jq -r '.prefix')
            repo=$(echo "$row"   | jq -r '.repo')

            echo "::group::Tag split $TAG for $prefix -> $repo"
            # Split from the tag ref so the package tag points to the correct subtree commit
            commit=$(splitsh-lite --prefix="$prefix" --origin="refs/tags/$TAG" || true)
            if [ -z "$commit" ]; then
              echo "No changes for $prefix at tag $TAG; skipping."
              echo "::endgroup::"
              continue
            fi

            # Create (or move) the tag locally at the split commit, then push it
            git tag -f "$TAG" "$commit"
            git push "$repo" "refs/tags/$TAG" --force
            echo "::endgroup::"
          done
