<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\Component\Config\Definition\Configurator;

use Symfony\AI\Store\Bridge\Postgres\Distance as PostgresDistance;
use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;

return (new ArrayNodeDefinition('postgres'))
    ->useAttributeAsKey('name')
    ->arrayPrototype()
        ->children()
            ->stringNode('connection')->cannotBeEmpty()->end()
            ->stringNode('dsn')->cannotBeEmpty()->end()
            ->stringNode('username')->end()
            ->stringNode('password')->end()
            ->stringNode('table_name')->end()
            ->stringNode('vector_field')->defaultValue('embedding')->end()
            ->enumNode('distance')
                ->info('Distance metric to use for vector similarity search')
                ->enumFqcn(PostgresDistance::class)
                ->defaultValue(PostgresDistance::L2)
            ->end()
            ->stringNode('dbal_connection')->cannotBeEmpty()->end()
            ->arrayNode('hybrid')
                ->info('Enable hybrid search combining pgvector (semantic) and Full-Text Search (lexical) using RRF')
                ->canBeEnabled()
                ->children()
                    ->stringNode('content_field')->defaultValue('content')->end()
                    ->floatNode('semantic_ratio')
                        ->info('Ratio between semantic (vector) and keyword (FTS) search. 0.0 = pure FTS, 0.5 = balanced, 1.0 = pure semantic')
                        ->defaultValue(1.0)
                        ->min(0.0)
                        ->max(1.0)
                    ->end()
                    ->stringNode('language')
                        ->info('PostgreSQL text search configuration (e.g., "simple", "english", "french"). Default: "simple" (multilingual)')
                        ->defaultValue('simple')
                    ->end()
                    ->stringNode('text_search_strategy')
                        ->info('Text search strategy: "native" for PostgreSQL FTS (ts_rank_cd) or "bm25" for BM25 ranking (requires plpgsql_bm25 extension)')
                        ->defaultValue('native')
                    ->end()
                    ->stringNode('bm25_language')
                        ->info('BM25 language code for stemming (e.g., "en", "fr", "es", "de", "it", "pt", "nl", "ru", "ar", "zh"). Default: "en"')
                        ->defaultValue('en')
                    ->end()
                    ->integerNode('rrf_k')
                        ->info('RRF (Reciprocal Rank Fusion) constant. Higher = more equal weighting. Default: 60')
                        ->defaultValue(60)
                        ->min(1)
                    ->end()
                    ->floatNode('default_max_score')
                        ->info('Default maximum distance threshold for filtering results (optional)')
                        ->defaultNull()
                    ->end()
                    ->floatNode('default_min_score')
                        ->info('Default minimum RRF score threshold for filtering results (optional)')
                        ->defaultNull()
                    ->end()
                    ->booleanNode('normalize_scores')
                        ->info('Normalize scores to 0-100 range for better readability')
                        ->defaultTrue()
                    ->end()
                    ->floatNode('fuzzy_primary_threshold')
                        ->info('Primary threshold for fuzzy matching (pg_trgm word_similarity). Default: 0.25')
                        ->defaultValue(0.25)
                        ->min(0.0)
                        ->max(1.0)
                    ->end()
                    ->floatNode('fuzzy_secondary_threshold')
                        ->info('Secondary threshold for fuzzy matching with double validation. Default: 0.2')
                        ->defaultValue(0.2)
                        ->min(0.0)
                        ->max(1.0)
                    ->end()
                    ->floatNode('fuzzy_strict_threshold')
                        ->info('Strict similarity threshold for double validation. Default: 0.15')
                        ->defaultValue(0.15)
                        ->min(0.0)
                        ->max(1.0)
                    ->end()
                    ->floatNode('fuzzy_weight')
                        ->info('Weight of fuzzy matching vs FTS in hybrid search. 0.0 = disabled, 0.5 = equal, 1.0 = fuzzy only')
                        ->defaultValue(0.5)
                        ->min(0.0)
                        ->max(1.0)
                    ->end()
                    ->arrayNode('searchable_attributes')
                        ->info('Searchable attributes with field-specific boosting. Each attribute creates a separate tsvector column.')
                        ->useAttributeAsKey('name')
                        ->arrayPrototype()
                            ->children()
                                ->floatNode('boost')
                                    ->info('Boost multiplier for this field (e.g., 2.0 = twice as important). Default: 1.0')
                                    ->defaultValue(1.0)
                                    ->min(0.0)
                                ->end()
                                ->scalarNode('metadata_key')
                                    ->info('JSON path to extract value from metadata (e.g., "title", "description")')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ->end()
        ->validate()
            ->ifTrue(static fn ($v) => !isset($v['dsn']) && !isset($v['dbal_connection']) && !isset($v['connection']))
            ->thenInvalid('Either "dsn", "dbal_connection", or "connection" must be configured.')
        ->end()
        ->validate()
            ->ifTrue(static fn ($v) => (int) isset($v['dsn']) + (int) isset($v['dbal_connection']) + (int) isset($v['connection']) > 1)
            ->thenInvalid('Only one of "dsn", "dbal_connection", or "connection" can be configured.')
        ->end()
    ->end();
